// refs: https://www.postgresql.org/docs/7.2/sql-createtable.html
//       https://www.postgresql.org/docs/current/ddl-constraints.html
//       https://www.postgresql.org/docs/19/datatype.html
//       https://www.postgresql.org/docs/current/ddl-identity-columns.html

CREATE TABLE PATIENT_CARE_ASSIGNMENT (
    _ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    _PATIENTID BIGINT REFERENCES PATIENT (_id),
    _USERID BIGINT REFERENCES USER (_id),
    CARE_START_TIMESTAMP TIMESTAMP DEFAULT NOW() NOT NULL,
    CARE_END_TIMESTAMP TIMESTAMP NOT NULL
);

CREATE TABLE SITE (
  _ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  NAME VARCHAR(200) UNIQUE NOT NULL, 
  ADDRESS VARCHAR(200) NOT NULL, 
  MUNICIPAL_NAME VARCHAR(200) NOT NULL, 
  POSTAL_CODE VARCHAR(6) NOT NULL,
  CONSTRAINT SITE_UK UNIQUE (NAME, ADDRESS)
);


CREATE TABLE LOCATION (
  _ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  NAME VARCHAR(200) NOT NULL, 
  BUILDING VARCHAR(200), 
  WING VARCHAR(200), 
  FLOOR VARCHAR(200), 
  ROOM_INDENTIFIER VARCHAR(200), 
  NOTES VARCHAR(2000),
  _SITEID BIGINT NOT NULL REFERENCES SITE (_id),
  CONSTRAINT LOCATION_UK UNIQUE (NAME, BUILDING)
);


CREATE TABLE PATIENT (
  _ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  LEGAL_FIRST_NAME VARCHAR(100), 
  LEGAL_LAST_NAME VARCHAR(100), 
  LEGAL_MIDDLE_NAMES VARCHAR(100), 
  SIN NUMBER(7) UNIQUE, 
  BIRTHDATE TIMESTAMP, 
  _LOCATIONID BIGINT REFERENCES LOCATION (_id),
  CONSTRAINT SITE_UK UNIQUE (LEGAL_FIRST_NAME, LEGAL_MIDDLE_NAMES, LEGAL_LAST_NAME, BIRTHDATE)
);


CREATE TABLE INTERVENTION (
  _ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  INTERVENTION_CODE VARCHAR(10),
  DESCRIPTION VARCHAR(2000),
  NOTES VARCHAR(2000),  
  _LOCATIONID BIGINT REFERENCES LOCATION (_id),
  _USERID BIGINT REFERENCES USER (_id)
);

CREATE TABLE ENCOUNTER (
  _ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  ADMIT_TIMESTAMP TIMESTAMP DEFAULT NOW(),
  ADMIT_NOTES VARCHAR(2000),
  DISCHARGE_TIMESTAMP DATETIME, 
  DISCHARGE_NOTES VARCHAR(2000),  
  _PATIENTID BIGINT REFERENCES PATIENT (_id),
  _INTERVENTIONID BIGINT REFERENCES INTERVENTION (_id),
  _SITEID BIGINT REFERENCES SITE (_id)
);

CREATE TABLE USER_PERMISSION (
  _ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  ACTIVE_FLAG VARCHAR(1),
  _USERID BIGINT REFERENCES USER (_id),
  _DEPARTMENTID BIGINT REFERENCES DEPARTMENT (_id),
  _ROLEID BIGINT REFERENCES ROLE (_id),
  _PERMISSIONID BIGINT REFERENCES PERMISSION (_id),
  CONSTRAINT SITE_UK UNIQUE (_USERID, _DEPARTMENTID, _ROLEID, _PERMISSIONID)
);

-------------- REFERENCE/CODE TABLES --------------


CREATE TABLE USER_PERMISSION (
  _ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  ACTIVE_FLAG VARCHAR(1),
  _USERID BIGINT REFERENCES USER (_id),
  _DEPARTMENTID BIGINT REFERENCES DEPARTMENT (_id),
  _ROLEID BIGINT REFERENCES ROLE (_id),
  _PERMISSIONID BIGINT REFERENCES PERMISSION (_id),
  CONSTRAINT SITE_UK UNIQUE (_USERID, _DEPARTMENTID, _ROLEID, _PERMISSIONID)
);

CREATE TABLE DEPARTMENT (
  _ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME VARCHAR(100) UNIQUE  NOT NULL, 
  EXPIRY_TIMESTAMP TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE TABLE ROLE (
  _ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME VARCHAR(100) UNIQUE  NOT NULL, 
  EXPIRY_TIMESTAMP TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE TABLE PERMISSION (
  _ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME VARCHAR(100) UNIQUE  NOT NULL, 
  EXPIRY_TIMESTAMP TIMESTAMP DEFAULT NOW() NOT NULL
);

---------------


CREATE TABLE FEATURE_PRIORITY (
  _ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  NAME VARCHAR(100) UNIQUE  NOT NULL, 
  ACTIVE_FLAG VARCHAR(1) NOT NULL,
  PRIORITY NUMBER(10) NOT NULL,
  WEIGHT NUMBER(10) NOT NULL,
  CALCULATION_TIMESTAMP TIMESTAMP DEFAULT NOW() NOT NULL,
  _USERID BIGINT REFERENCES USER (_id),
  _DEPARTMENTID BIGINT REFERENCES DEPARTMENT (_id),
  CONSTRAINT SITE_UK UNIQUE (_USERID, _DEPARTMENTID, _ROLEID, _PERMISSIONID)
)


CREATE TABLE AUDIT_RECORD (
  _ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  AUDIT_METADATA VARCHAR(500) NOT NULL,
  AUDIT_CLOB VARCHAR(2000) NOT NULL,
  AUDIT_TIMESTAMP TIMESTAMP DEFAULT NOW() NOT NULL,
  _USERID BIGINT REFERENCES USER (_id) NOT NULL
);