[package]
name = "MapleEMR"
version = "0.1.0"
edition = "2024" # Cargo edition, not the package

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
log = "0.4"
sqlx = { version = "0.8", features = ["runtime-tokio", "tls-rustls", "postgres", "macros", "migrate", "uuid", "chrono"] }
actix-web = "4.14.0"
chrono = {version = "0.4.45", features = ["serde"] }
ndarray = "0.17.2"
ort = { version = "2.0.0-rc.12", features = [ "fetch-models" ] }
tokenizers = { version = "0.23.1", default-features = false, features = [ "onig" ] }
derive_more = "2.1.1"
actix-cors = "0.7.1"
actix-files = "0.6.10"
actix-session = { version = "0.11.0", features = ["cookie-session", "redis-session"] }
validator = { version = "0.21.0", features = ["derive"] }
rand = "0.10.2"
thread-rng = "0.0.0"

[features]
load-dynamic = [ "ort/load-dynamic" ]

cuda = [ "ort/cuda" ]
tensorrt = [ "ort/tensorrt" ]
openvino = [ "ort/openvino" ]
onednn = [ "ort/onednn" ]
directml = [ "ort/directml" ]
nnapi = [ "ort/nnapi" ]
coreml = [ "ort/coreml" ]
xnnpack = [ "ort/xnnpack" ]
rocm = [ "ort/rocm" ]
acl = [ "ort/acl" ]
armnn = [ "ort/armnn" ]
tvm = [ "ort/tvm" ]
migraphx = [ "ort/migraphx" ]
rknpu = [ "ort/rknpu" ]
vitis = [ "ort/vitis" ]
cann = [ "ort/cann" ]
qnn = [ "ort/qnn" ]
webgpu = [ "ort/webgpu" ]
