// refs: https://www.postgresql.org/docs/7.2/sql-createtable.html
//       https://www.postgresql.org/docs/current/ddl-constraints.html
//       https://www.postgresql.org/docs/19/datatype.html
//       https://www.postgresql.org/docs/current/ddl-identity-columns.html

-------------- PRIMARY TABLES --------------

CREATE TABLE USERS (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  NAME VARCHAR(200) NOT NULL, 
  USERNAME VARCHAR(50) UNIQUE NOT NULL, 
  EMAIL VARCHAR(100), 
  CREATED_TIMESTAMP TIMESTAMP DEFAULT NOW(),
  PASSWORD VARCHAR(30),
  SITE_ID BIGINT NOT NULL REFERENCES SITE (ID),
  CONSTRAINT USERS_EMAIL_UK UNIQUE (EMAIL)
);


CREATE TABLE SITE (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  NAME VARCHAR(200) UNIQUE NOT NULL, 
  ADDRESS VARCHAR(200) NOT NULL, 
  MUNICIPAL_NAME VARCHAR(200) NOT NULL, 
  POSTAL_CODE VARCHAR(6) NOT NULL,
  CONSTRAINT SITE_UK UNIQUE (NAME, ADDRESS)
);


CREATE TABLE LOCATION(
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  NAME VARCHAR(200) NOT NULL, 
  BUILDING VARCHAR(200), 
  WING VARCHAR(200), 
  FLOOR VARCHAR(200), 
  ROOM_IDENTIFIER VARCHAR(200), 
  ACTIVE_FLAG VARCHAR(1) NOT NULL DEFAULT 'Y',
  NOTES VARCHAR(2000),
  SITE_ID BIGINT NOT NULL REFERENCES SITE (ID),
  CONSTRAINT LOCATION_UK UNIQUE (NAME, ROOM_IDENTIFIER)
);


CREATE TABLE PATIENT (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  LEGAL_FIRST_NAME VARCHAR(100) NOT NULL, 
  LEGAL_LAST_NAME VARCHAR(100), 
  LEGAL_MIDDLE_NAMES VARCHAR(100), 
  SIN NUMERIC(9) UNIQUE, 
  BIRTHDATE TIMESTAMP, 
  CONSTRAINT PATIENT_UK UNIQUE (LEGAL_FIRST_NAME, LEGAL_MIDDLE_NAMES, LEGAL_LAST_NAME, BIRTHDATE)
);


CREATE TABLE INTERVENTION (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  INTERVENTION_CODE VARCHAR(10) NOT NULL,
  DESCRIPTION VARCHAR(2000 NOT NULL),
  NOTES VARCHAR(2000),
  STATUS_CODE VARCHAR(20) NOT NULL,
  LOCATION_ID BIGINT REFERENCES LOCATION (ID),
  ENCOUNTER_ID BIGINT REFERENCES ENCOUNTER (ID) NOT NULL,
  USERS_ID BIGINT REFERENCES USERS (ID)
);

CREATE TABLE ENCOUNTER (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  ADMIT_TIMESTAMP TIMESTAMP DEFAULT NOW() NOT NULL,
  ADMIT_NOTES VARCHAR(2000) NOT NULL,
  DISCHARGE_TIMESTAMP TIMESTAMP, 
  DISCHARGE_NOTES VARCHAR(2000),  
  PATIENT_ID BIGINT REFERENCES PATIENT (ID) NOT NULL,
  LOCATION_ID BIGINT REFERENCES LOCATION (ID)
);

CREATE TABLE USER_PERMISSION (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  ACTIVE_FLAG VARCHAR(1) NOT NULL DEFAULT 'Y',
  USERS_ID BIGINT REFERENCES USERS (ID) NOT NULL,
  DEPARTMENT_ID BIGINT REFERENCES DEPARTMENT (ID) NOT NULL,
  ROLE_ID BIGINT REFERENCES ROLE (ID) NOT NULL,
  PERMISSION_ID BIGINT REFERENCES PERMISSION (ID) NOT NULL,
  SITE_ID BIGINT REFERENCES SITE (ID),
  CONSTRAINT USER_PERMISSION_UK UNIQUE (USERS_ID, DEPARTMENT_ID, ROLE_ID, PERMISSION_ID)
);

CREATE TABLE PATIENT_CARE_ASSIGNMENT (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  ASSIGNED_TIMESTAMP TIMESTAMP,
  EXPIRED_TIMESTAMP TIMESTAMP,
  CARE_TYPE_CODE VARCHAR(20),
  RATIONALE VARCHAR(2000),
  ENCOUNTER_ID BIGINT REFERENCES ENCOUNTER (ID),
  INTERVENTION_ID BIGINT REFERENCES INTERVENTION (ID),
  USERS_ID BIGINT REFERENCES USERS (ID) NOT NULL
);

-------------- SECONDARY REFERENCE/CODE TABLES --------------

CREATE TABLE AUDIT_RECORD (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  AUDIT_METADATA VARCHAR(500) NOT NULL,
  AUDIT_CLOB VARCHAR(2000) NOT NULL,
  AUDIT_TIMESTAMP TIMESTAMP DEFAULT NOW() NOT NULL,
  USERS_ID BIGINT REFERENCES USERS (ID) NOT NULL
);

CREATE TABLE FEATURE_PRIORITY (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  NAME VARCHAR(100) UNIQUE  NOT NULL, 
  ACTIVE_FLAG VARCHAR(1) NOT NULL DEFAULT 'Y',
  PRIORITY NUMERIC(10) NOT NULL,
  WEIGHT NUMERIC(10) NOT NULL,
  LAST_CALCULATION_DATE TIMESTAMP DEFAULT NOW() NOT NULL,
  USERS_ID BIGINT REFERENCES USERS (ID),
  DEPARTMENT_ID BIGINT REFERENCES DEPARTMENT (ID),
  PERMISSION_ID BIGINT REFERENCES PERMISSION (ID),
  CONSTRAINT FEATURE_PRIORITY_UK UNIQUE (USERS_ID, DEPARTMENT_ID, PERMISSION_ID)
);



-------------- POSSIBLY DO-NOT-IMPLEMENT TABLES --------------

CREATE TABLE DEPARTMENT (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME VARCHAR(100) UNIQUE  NOT NULL, 
  EXPIRY_DATETIME TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE TABLE ROLE (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME VARCHAR(100) UNIQUE  NOT NULL, 
  EXPIRY_DATETIME TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE TABLE PERMISSION (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME VARCHAR(100) UNIQUE  NOT NULL, 
  EXPIRY_DATETIME TIMESTAMP DEFAULT NOW() NOT NULL
);