CREATE DATABASE csm500;
\c csm500

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE,
    password VARCHAR(30) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

// refs: https://www.postgresql.org/docs/7.2/sql-createtable.html
//       https://www.postgresql.org/docs/current/ddl-constraints.html

CREATE TABLE SITE AS (
  _ID INT PRIMARY KEY, 
  NAME VARCHAR(200) UNIQUE NOT NULL, 
  ADDRESS VARCHAR(200) NOT NULL, 
  MUNICIPAL_NAME VARCHAR(200) NOT NULL, 
  POSTAL_CODE VARCHAR(6) NOT NULL,
  CONSTRAINT Site_UK UNIQUE (NAME, ADDRESS)
);



CREATE TABLE LOCATION AS (
  _ID INT PRIMARY KEY, 
  NAME VARCHAR(200) NOT NULL, 
  BUILDING VARCHAR(200), 
  WING VARCHAR(200), 
  FLOOR VARCHAR(200), 
  ROOM_INDENTIFIER VARCHAR(200), 
  NOTES VARCHAR(2000),
  _SITEID INT NOT NULL,
  CONSTRAINT Site_UK UNIQUE (NAME, BUILDING)
);



CREATE TABLE PATIENT AS (
  _ID INT PRIMARY KEY, 
  LEGAL_FIRST_NAME VARCHAR(100), 
  LEGAL_LAST_NAME VARCHAR(100), 
  LEGAL_MIDDLE_NAMES VARCHAR(100), 
  SIN NUMBER(7) UNIQUE, 
  BIRTHDATE TIMESTAMP, 
  _LOCATIONID INT,
  CONSTRAINT SITE_UK UNIQUE (LEGAL_FIRST_NAME, LEGAL_MIDDLE_NAMES, LEGAL_LAST_NAME, BIRTHDATE)
);



CREATE TABLE INTERVENTION AS (
  _ID INT PRIMARY KEY, 
  INTERVENTION_CODE VARCHAR(10),
  DESCRIPTION VARCHAR(2000),
  NOTES VARCHAR(2000),  
  _LOCATIONID INT,
  _USERID INT
);

CREATE TABLE ENCOUNTER AS (
  _ID INT PRIMARY KEY, 
  ADMIT_DATETIME TIMESTAMP DEFAULT NOW(),
  ADMIT_NOTES VARCHAR(2000),
  DISCHARGE_DATETIME DATETIME, 
  DISCHARGE_NOTES VARCHAR(2000),  
  _PATIENTID INT,
  _INTERVENTIONID INT
  _SITEID INT
);

CREATE TABLE USER_PERMISSION AS (
  _ID INT PRIMARY KEY, 
  ACTIVE_FLAG VARCHAR(1),
  _USERID INT,
  _DEPARTMENTID INT,
  _ROLEID INT,
  _PERMISSIONID INT,
  CONSTRAINT SITE_UK UNIQUE (_USERID, _DEPARTMENTID, _ROLEID, _PERMISSIONID)
);



CREATE TABLE FEATURE_PRIORITY AS (
  _ID INT PRIMARY KEY, 
  NAME VARCHAR(100) UNIQUE  NOT NULL, 
  ACTIVE_FLAG VARCHAR(1) NOT NULL,
  PRIORITY NUMBER(10) NOT NULL,
  WEIGHT NUMBER(10) NOT NULL,
  LAST_CALCULATION_DATE TIMESTAMP DEFAULT NOW() NOT NULL,
  _USERID INT,
  _DEPARTMENTID INT,
  CONSTRAINT SITE_UK UNIQUE (_USERID, _DEPARTMENTID, _ROLEID, _PERMISSIONID)
);



CREATE TABLE AUDIT_RECORD AS (
  _ID INT PRIMARY KEY, 
  AUDIT_METADATA VARCHAR(500) NOT NULL,
  AUDIT_CLOB VARCHAR(2000) NOT NULL,
  AUDIT_DATETIME TIMESTAMP DEFAULT NOW() NOT NULL
  _USERID INT NOT NULL
);